# Generated by Django 4.2.4 on 2023-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinBalance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gnum',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='split',
            name='gnum',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
