# Generated by Django 4.2.4 on 2023-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinBalance', '0002_payment_gnum_split_gnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
