# Generated by Django 4.2.4 on 2023-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinBalance', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
