# Generated by Django 4.2.4 on 2023-09-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinBalance', '0005_comment_cpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cpic',
        ),
    ]
